name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: ritneshthakur
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#00FF7F"   # Neon green snake
          color_dots: "#282C34,#3C4048,#444C56,#586069,#6A737D"  # GitHub dark mode palette
          animation_duration: 3
          mask: "soft"

      - name: Push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
